### ISSUE TITLE
Raising Parse_error in ocamlyacc parser action can induce segfault

### ISSUE THREAD

**Issue by InnocentusLime** [ocaml/ocaml#10080]
Hello! 
I was writing a big project which used `ocamlyacc` and `ocamllex` to generate some parsers and I've just got it to segfault. Judging by the backtrace printed by GDB, the problems is somewhere deep in the `ocamlyacc`

```
#0  0x00005555555d2d14 in caml_apply2 ()
#1  0x0000555555601ca2 in camlStdlib__parsing__loop_295 () at parsing.ml:142
#2  0x0000555555601af9 in camlStdlib__parsing__yyparse_290 () at parsing.ml:164
#3  0x00005555555d3f54 in camlDune__exe__Top__read_command_terminal_304 () at bin/top.ml:20
#4  0x00005555555d4d4c in camlDune__exe__Top__top_level_main_547 () at bin/top.ml:157
#5  0x00005555555d3a70 in camlDune__exe__Main__launch_1078 () at bin/main.ml:156
#6  0x00005555555d3c8f in camlDune__exe__Main__entry () at bin/main.ml:172
#7  0x00005555555d09e9 in caml_program ()
#8  0x0000555555641e90 in caml_start_program ()
#9  0x0000555555642285 in caml_startup_common ()
#10 0x00005555556422cf in caml_startup ()
#11 0x00005555555d0662 in main ()
```
If it can help, I will send the whole project together with steps to reproduce it

**Comment by DemiMarie** [comment]
Are you using `Obj` or any externals anywhere?  `ocamlyacc` generated code uses `Obj` internally; that’s normal, but if you use it yourself, that could be the culprit.

**Comment by gasche** [comment]
I made [a comment on the project directly](https://github.com/InnocentusLime/TRust/commit/365e4b166894cb6f595fbc7aff73749a70557ecd#r45264138) on a possible misuse of `error` tokens, to be investigated by the reporter.

**Comment by InnocentusLime** [comment]
@DemiMarie No, the project uses Ocaml's stdlib only and no code uses `Obj` directly
@gasche I have replies to the comment on the project. To sum up, the `segfault` still seems to show up. I am working on a smaller example to reproduce it

**Comment by InnocentusLime** [comment]
I have generated the minimal example to reproduce the crash. 

### The files

The example consists 4 files.

irTerml.ml
```ml
type term =
| Var of string
| Abs of string * term * term
| BoolRec of term * term * term * term
```
ast.mly
```ml
%token <string> IDENT
%token LBRACE RBRACE
%token LSQBR RSQBR
%token IF ELSE
%token SLASH DOT
%token EOF

%start ir_term
%type <IrTerm.term> ir_term
%%
conditional_ir_term_start:
| IF LSQBR ir_term RSQBR ir_term { fun on_true on_false -> IrTerm.BoolRec ($3, $5, on_true, on_false) }
| IF LSQBR error { raise Parse_error }
| IF error { raise Parse_error }
| IF LSQBR ir_term RSQBR error { raise Parse_error }
atom_ir_term:
| conditional_ir_term_start LBRACE ir_term RBRACE ELSE LBRACE ir_term RBRACE { $1 $3 $7 }
| IDENT { IrTerm.Var $1 }
ir_term:
| atom_ir_term { $1 }
| SLASH IDENT DOT { IrTerm.Var "" }
```
lex.mll
```ml
{
  open Ast

  let keyword_table = (
    let temp = Hashtbl.create 256 in
    Hashtbl.add temp "if" IF; 
    Hashtbl.add temp "else" ELSE; 
    temp
  )
}

let lower_letter = ['a' - 'z']
let upper_letter = ['A' - 'Z']
let letter = lower_letter | upper_letter

let ident = letter*

rule lex =
parse          
| ident as s { if Hashtbl.mem keyword_table s then Hashtbl.find keyword_table s else IDENT s }
| '{' { LBRACE }
| '}' { RBRACE }
| '[' { LSQBR }
| ']' { RSQBR }
| '.' { DOT }
| '\\' { SLASH }
| eof { EOF }
```

main.ml
```ml
let _ = Ast.ir_term Lex.lex (Lexing.from_string "if[\\x]\\x{x}else{x}")
```

### Steps to cause a segfault

1. Call `ocamlyacc ast.mly`
2. Call `ocamllex lex.mll`
3. Call `ocamlc irTerm.ml ast.mli ast.ml lex.ml main.ml -o main` (`ocamlopt` produces a segfaulting program too)
4. Call `./main`

### Version info

`ocamlc --version`: 4.08.1
`ocamllex -v`: The OCaml lexer generator, version 4.08.1

### Backtrace after compiling with `ocamlopt` and calling `gdb`

```
#0  0x000055555559cc24 in caml_apply2 ()
#1  0x00005555555ab112 in camlStdlib__parsing__loop_295 () at parsing.ml:142
#2  0x00005555555aaf69 in camlStdlib__parsing__yyparse_290 () at parsing.ml:164
#3  0x000055555559cccf in camlMain__entry ()
#4  0x000055555559a919 in caml_program ()
#5  0x00005555555e2040 in caml_start_program ()
#6  0x00005555555e28b5 in caml_startup_common ()
#7  0x00005555555e28ff in caml_startup ()
#8  0x000055555559a662 in main ()
```

**Comment by lthls** [comment]
I think the problem is caused by the `raise Parse_error` actions. I'm not an expert by far but from what I've seen of the code, it can be used from a non-error rule to make the parser treat it as a parsing error, recoverable by the `error` token in previous rules.
But calling it from a rule containing an `error` token messes with the parser's error handling logic, which (if I understand correctly) assumes that an action that raises `Parse_error` has consumed a regular argument last, and not an error.
In this particular case, the parser actually manages to recover from a number of parsing errors for the `conditional_ir_term_start` non-terminal token, but the semantic value associated with it ends up being the one it read from a terminal, constant token that it discarded somewhere in the process. This results in the rule for `atom_ir_term` trying to call `()`, which is obviously not a function, so it segfaults.

My suggestion to @InnocentusLime  would be to stop using `Parse_error` and instead use your own exception. Hopefully this should fix the problem.

I think we should keep this issue open until we've found some kind of fix though (and maybe we should check that menhir handles this case better). At the very least I'd expect some warning that `Parse_error` should not be used from `error` rules.

**Comment by InnocentusLime** [comment]
I am very happy to announce that @lthls's solution **did** fix the problem. After replacing `Parse_error` with a quickly crafted exception `Foo`, the test program properly terminated with an error. 

I do agree that there's still an issue. It indeed would be nice to either have a fix for parser's logic to not make safe looking code segfault *or* get some kind of lint, which would notify the user that their code will most likely segfault.

**Comment by DemiMarie** [comment]
> I think we should keep this issue open until we've found some kind of fix though (and maybe we should check that menhir handles this case better). At the very least I'd expect some warning that `Parse_error` should not be used from `error` rules.

What about `try semantic_action with Parse_error _ -> raise Invalid_argument "Parse_error thrown from error rule"`?
