### ISSUE TITLE
`dumpobj` tool crashes

### ISSUE THREAD

**Issue by OlivierNicole** [ocaml/ocaml#11061]
As of revision f022f9b9d, the executable `tools/dumpobj` crashes with a segmentation fault when called on a simple bytecode program. The same is true of `tools/dumpobj.opt`.
```
$ cat tmp.ml
let () =
  let x = 42 in
  let x = x + x in
  Printf.printf "%d\n" x
$ ocamlc tmp.ml
$ ~/path/to/compiler/tools/dumpobj a.out
## start of ocaml dump of "a.out"
zsh: segmentation fault (core dumped) ~/path/to/compiler/tools/dumpobj a.out
$ ~/path/to/compiler/tools/dumpobj.opt a.out
## start of ocaml dump of "a.out"
zsh: segmentation fault (core dumped) ~/path/to/compiler/tools/dumpobj.opt a.out
```

GDB backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000822403 in do_compare_val (stk=stk@entry=0x7fffffffbee0, v1=0, v2=0, total=total@entry=0) at compare.c:150
150	      switch (Tag_val(v1)) {
(gdb) bt
#0  0x0000000000822403 in do_compare_val (stk=stk@entry=0x7fffffffbee0, v1=0, v2=0, total=total@entry=0) at compare.c:150
#1  0x00000000008229b7 in compare_val (total=0, v2=<optimized out>, v1=<optimized out>) at compare.c:97
#2  caml_equal (v1=<optimized out>, v2=<optimized out>) at compare.c:316
#3  <signal handler called>
#4  0x000000000052b4d1 in camlDumpobj__same_custom_1113 () at dumpobj.ml:114
#5  0x000000000052b7b5 in camlDumpobj__print_obj_1160 () at dumpobj.ml:135
#6  0x000000000052c53e in camlDumpobj__print_instr_1317 () at dumpobj.ml:440
#7  0x000000000052ca20 in camlDumpobj__print_code_1336 () at dumpobj.ml:482
#8  0x000000000052d23f in camlDumpobj__arg_fun_1536 () at dumpobj.ml:574
#9  0x00000000007f51d2 in camlStdlib__Arg__parse_and_expand_argv_dynamic_aux_601 () at arg.ml:279
#10 0x00000000007f641b in camlStdlib__Arg__parse_expand_830 () at arg.ml:287
#11 0x000000000052d333 in camlDumpobj__main_1540 () at dumpobj.ml:582
#12 0x000000000052da6f in camlDumpobj__entry () at dumpobj.ml:585
#13 0x00000000005273ab in caml_program ()
#14 <signal handler called>
#15 caml_startup (argv=<optimized out>) at startup_nat.c:136
#16 0x000000000083faf5 in caml_main (argv=<optimized out>) at startup_nat.c:142
#17 0x00000000005268bc in main (argc=<optimized out>, argv=<optimized out>) at main.c:37
```

**Comment by OlivierNicole** [comment]
To avoid duplication of work: I am looking at this now.
