### ISSUE TITLE
tests/lib-systhreads/testyield.ml: Timeout expired, killing all child processes on NetBSD 9

### ISSUE THREAD

**Issue by omasanori** [ocaml/ocaml#12415]
From <https://builds.sr.ht/~omasanori/job/1028686>:
```
List of failed tests:
    tests/lib-systhreads/'testyield.ml' with 1.1.1 (bytecode) Timeout expired, killing all child processes
    tests/lib-systhreads/'testyield.ml' with 1.1.2 (native) Timeout expired, killing all child processes
```
I have not identify the root cause since I have no NetBSD machine locally. Can anyone confirm this with Inria CI?

**Comment by VoxSciurorum** [comment]
I reproduced this on NetBSD 10.0, OCaml 4.14.3+dev0-2024-03-14, armv7.
I compiled testyield.ml to a bytecode program, ran it under gdb, stopped after a few seconds and got this output:
```
[ 100691.8560534] load: 1.04  cmd: ocamlrun 5153 [0x708304f8/1 0x70830d50/1 parked select parked parked] 1.75u 4.70s 10% 2112k

Thread 7 received signal SIGINFO, Information request.
0x708304f8 in _lwp_unpark () from /usr/lib/libc.so.12
(gdb) i threads
  Id   Target Id                    Frame 
  1    LWP 5153 of process 5153 ""  0x70830d50 in ___lwp_park60 () from /usr/lib/libc.so.12
  2    LWP 1364 of process 5153 ""  0x70830d50 in ___lwp_park60 () from /usr/lib/libc.so.12
  3    LWP 6701 of process 5153 ""  0x708300c0 in _sys___select50 () from /usr/lib/libc.so.12
  4    LWP 7654 of process 5153 ""  0x70830d50 in ___lwp_park60 () from /usr/lib/libc.so.12
  5    LWP 7471 of process 5153 ""  0x70830d50 in ___lwp_park60 () from /usr/lib/libc.so.12
  6    LWP 23711 of process 5153 "" 0x708304f8 in _lwp_unpark () from /usr/lib/libc.so.12
* 7    process 5153                 0x708304f8 in _lwp_unpark () from /usr/lib/libc.so.12
(gdb) bt
#0  0x708304f8 in _lwp_unpark () from /usr/lib/libc.so.12
#1  0x708a8db4 in pthread.mutex_wakeup.constprop () from /usr/lib/libpthread.so.1
#2  0x708a9504 in pthread_mutex_unlock () from /usr/lib/libpthread.so.1
#3  0x708aa718 in pthread_cond_timedwait () from /usr/lib/libpthread.so.1
#4  0x70422dd8 in st_thread_yield (m=0x7043406c <caml_master_lock>) at st_posix.h:189
#5  caml_thread_yield (unit=<optimized out>) at st_stubs.c:734
#6  0x00037550 in caml_interprete (prog=0x0, prog@entry=0x5da40 <callback_code>, 
    prog_size=prog_size@entry=28) at interp.c:930
#7  0x0002d678 in caml_callbackN_exn (closure=closure@entry=1885832664, narg=narg@entry=1, 
    args=args@entry=0x6f0e9fd4) at callback.c:70
#8  0x0002d6d8 in caml_callback_exn (closure=closure@entry=1885832664, arg1=arg1@entry=1)
    at callback.c:79
#9  0x70422818 in caml_thread_start (arg=<optimized out>) at st_stubs.c:546
#10 0x708ac488 in pthread.create_tramp () from /usr/lib/libpthread.so.1
#11 0x70830b68 in __mknod50 () from /usr/lib/libc.so.12
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) t 7
Thread ID 7 has terminated.
(gdb) t 6
[Switching to thread 6 (LWP 23711 of process 5153)]
#0  0x708304f8 in _lwp_unpark () from /usr/lib/libc.so.12
(gdb) bt
#0  0x708304f8 in _lwp_unpark () from /usr/lib/libc.so.12
#1  0x708a8db4 in pthread.mutex_wakeup.constprop () from /usr/lib/libpthread.so.1
#2  0x708a9504 in pthread_mutex_unlock () from /usr/lib/libpthread.so.1
#3  0x708aa718 in pthread_cond_timedwait () from /usr/lib/libpthread.so.1
#4  0x70422dd8 in st_thread_yield (m=0x7043406c <caml_master_lock>) at st_posix.h:189
#5  caml_thread_yield (unit=<optimized out>) at st_stubs.c:734
#6  0x00037550 in caml_interprete (prog=0x0, prog@entry=0x5da40 <callback_code>, 
    prog_size=prog_size@entry=28) at interp.c:930
#7  0x0002d678 in caml_callbackN_exn (closure=closure@entry=1885832664, narg=narg@entry=1, 
    args=args@entry=0x6f0e9fd4) at callback.c:70
#8  0x0002d6d8 in caml_callback_exn (closure=closure@entry=1885832664, arg1=arg1@entry=1)
    at callback.c:79
#9  0x70422818 in caml_thread_start (arg=<optimized out>) at st_stubs.c:546
#10 0x708ac488 in pthread.create_tramp () from /usr/lib/libpthread.so.1
#11 0x70830b68 in __mknod50 () from /usr/lib/libc.so.12
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) t 5
[Switching to thread 5 (LWP 7471 of process 5153)]
#0  0x70830d50 in ___lwp_park60 () from /usr/lib/libc.so.12
(gdb) bt
#0  0x70830d50 in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x708aa74c in pthread_cond_timedwait () from /usr/lib/libpthread.so.1
#2  0x70422dd8 in st_thread_yield (m=0x7043406c <caml_master_lock>) at st_posix.h:189
#3  caml_thread_yield (unit=<optimized out>) at st_stubs.c:734
#4  0x00037550 in caml_interprete (prog=0x70838f6c <je_bin_infos>, 
    prog@entry=0x5da40 <callback_code>, prog_size=prog_size@entry=28) at interp.c:930
#5  0x0002d678 in caml_callbackN_exn (closure=closure@entry=1885832724, narg=narg@entry=1, 
    args=args@entry=0x6f4f9fd4) at callback.c:70
#6  0x0002d6d8 in caml_callback_exn (closure=closure@entry=1885832724, arg1=arg1@entry=1)
    at callback.c:79
#7  0x70422818 in caml_thread_start (arg=<optimized out>) at st_stubs.c:546
#8  0x708ac488 in pthread.create_tramp () from /usr/lib/libpthread.so.1
#9  0x70830b68 in __mknod50 () from /usr/lib/libc.so.12
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) t 4
[Switching to thread 4 (LWP 7654 of process 5153)]
#0  0x70830d50 in ___lwp_park60 () from /usr/lib/libc.so.12
(gdb) bt
#0  0x70830d50 in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x708aa74c in pthread_cond_timedwait () from /usr/lib/libpthread.so.1
#2  0x70422000 in st_masterlock_acquire (m=0x7043406c <caml_master_lock>) at st_posix.h:137
#3  caml_thread_leave_blocking_section () at st_stubs.c:244
#4  0x0001dc10 in caml_leave_blocking_section () at signals.c:175
#5  0x704227f0 in caml_thread_start (arg=0x704620e0) at st_stubs.c:535
#6  0x708ac488 in pthread.create_tramp () from /usr/lib/libpthread.so.1
#7  0x70830b68 in __mknod50 () from /usr/lib/libc.so.12
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) t 3
[Switching to thread 3 (LWP 6701 of process 5153)]
#0  0x708300c0 in _sys___select50 () from /usr/lib/libc.so.12
(gdb) bt
#0  0x708300c0 in _sys___select50 () from /usr/lib/libc.so.12
#1  0x708a7024 in __select50 () from /usr/lib/libpthread.so.1
#2  0x70421c80 in caml_thread_tick (arg=<optimized out>) at st_posix.h:398
#3  0x708ac488 in pthread.create_tramp () from /usr/lib/libpthread.so.1
#4  0x70830b68 in __mknod50 () from /usr/lib/libc.so.12
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) t 2
[Switching to thread 2 (LWP 1364 of process 5153)]
#0  0x70830d50 in ___lwp_park60 () from /usr/lib/libc.so.12
(gdb) bt
#0  0x70830d50 in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x708aa74c in pthread_cond_timedwait () from /usr/lib/libpthread.so.1
#2  0x70422000 in st_masterlock_acquire (m=0x7043406c <caml_master_lock>) at st_posix.h:137
#3  caml_thread_leave_blocking_section () at st_stubs.c:244
#4  0x0001dc10 in caml_leave_blocking_section () at signals.c:175
#5  0x704227f0 in caml_thread_start (arg=0x70462070) at st_stubs.c:535
#6  0x708ac488 in pthread.create_tramp () from /usr/lib/libpthread.so.1
#7  0x70830b68 in __mknod50 () from /usr/lib/libc.so.12
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) t 1
[Switching to thread 1 (LWP 5153 of process 5153)]
#0  0x70830d50 in ___lwp_park60 () from /usr/lib/libc.so.12
(gdb) bt
#0  0x70830d50 in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x708aa74c in pthread_cond_timedwait () from /usr/lib/libpthread.so.1
#2  0x70422f40 in st_event_wait (e=0x704620a8) at st_posix.h:353
#3  caml_threadstatus_wait (wrapper=<optimized out>) at st_stubs.c:953
#4  caml_thread_join (th=<optimized out>) at st_stubs.c:746
#5  0x00037550 in caml_interprete (prog=0x70201078, prog_size=<optimized out>) at interp.c:930
#6  0x00039624 in caml_main (argv=0x7ffa495c) at startup_byt.c:588
#7  0x0003f468 in main (argc=<optimized out>, argv=<optimized out>) at main.c:37
(gdb) t 0
```
Stopped at a different time thread status was
```
  Id   Target Id                    Frame 
  1    LWP 5153 of process 5153 ""  0x70830d50 in ___lwp_park60 () from /usr/lib/libc.so.12
  2    LWP 1364 of process 5153 ""  0x70830d50 in ___lwp_park60 () from /usr/lib/libc.so.12
  3    LWP 6701 of process 5153 ""  0x708300c0 in _sys___select50 () from /usr/lib/libc.so.12
  4    LWP 7654 of process 5153 ""  0x70830d50 in ___lwp_park60 () from /usr/lib/libc.so.12
  5    LWP 7471 of process 5153 ""  0x70830d50 in ___lwp_park60 () from /usr/lib/libc.so.12
* 6    LWP 23711 of process 5153 "" 0x708304f8 in _lwp_unpark () from /usr/lib/libc.so.12
  7    process 5153                 0x708304f8 in _lwp_unpark () from /usr/lib/libc.so.12
```
