### ISSUE TITLE
Segfault during GC compaction

### ISSUE THREAD

**Issue by sadiqj** [ocaml/ocaml#9853]
In the case where:

-  there is only one major heap chunk
-  the only major heap chunk is fully used

the current GC compactor will segfault here:

https://github.com/ocaml/ocaml/blob/trunk/runtime/compact.c#L126

as `Chunk_next` will return 0.

A testcase which will reliably segfault 4.10.0, 4.10.1, 4.11.0 and trunk is:

````
let c = ref []

let () =
  for i = 0 to 1000000 do
    c := 0 :: !c;
    Gc.compact ()
 done
````

This was discovered while stress testing safepoints with the help of @mshinwell and @lpw25

**Comment by mshinwell** [comment]
cc @damiendoligez

**Comment by sadiqj** [comment]
This code also segfaults 4.00.0, which is the earliest version I seem to be able to build on my machine.

**Comment by avsm** [comment]
I just tried it on OCaml 3.12.1, where it also segfaults:

```
$ docker run -it debian/eol:wheezy
# apt-get update
# apt-get install ocaml-native-compilers
<create t.ml>
# ocamlopt.opt t.ml
# ./a.out 
Segmentation fault
```

**Comment by avsm** [comment]
I went back into memory lane, and... it's been around since roughly day 1 by the looks of it.

With Debian Potato, and OCaml 2.04 (`docker run -it debian/eol:potato`):

```
# ocaml      
        Objective Caml version 2.04
# ocamlopt.opt t.ml 
# gdb ./a.out 
GNU gdb 19990928
Copyright 1998 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "i686-pc-linux-gnu"...(no debugging symbols found)...
(gdb) run
Starting program: /./a.out 
(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...(no debugging symbols found)...
Program received signal SIGSEGV, Segmentation fault.
0x80508e6 in compact_allocate ()
(gdb) bt
#0  0x80508e6 in compact_allocate ()
#1  0x8050bb3 in compact_heap ()
#2  0x804f89a in gc_compaction ()
#3  0x804901f in T_entry ()
#4  0x8049ce9 in main ()
#5  0xf7eb6a42 in __libc_start_main () from /lib/libc.so.6
(gdb) 
```

**Comment by lpw25** [comment]
@damiendoligez
